### ISSUE TITLE
Syntax error:  "(" unexpected

### ISSUE THREAD

**Issue by amonetlol** [c-thun/10ify#2]
Installing Dependencies...
Setting Up Basic Files...
Installing Animation Tweaks...
Installing Dash to Panel...
Installing Arc Menu...
Modifying the look and feel
install.sh: 102: Syntax error: "(" unexpected

**Comment by ghost** [comment]
Try running the script again. If the problem persists, reply back here. I'm not sure why this is happening. Will spin a VM and check it

**Comment by ghost** [comment]
Have checked the code. Unable to reproduce. Manually run the script multiple times without this issue occurring ever again. Closing the issue
